manifest:
  remotes:
    - name: ThrowTheSwitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: Unity
      remote: ThrowTheSwitch
      revision: v2.5.2
      path: modules/test/cmock/vendor/unity
